service: livingodlife-backend

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-2

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: "npm" # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore

functions:
  app:
    handler: src/serverless.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
